---
## x86_64
# debian jessie
- name: Configuring /etc/apt/sources.list for debian jessie on x86_64
  ansible.builtin.set_fact:
    sources_filename: debian-jessie.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "jessie"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# debian stretch
- name: Configuring /etc/apt/sources.list for debian stretch on x86_64
  ansible.builtin.set_fact:
    sources_filename: debian-stretch.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "stretch"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# debian buster
- name: Configuring /etc/apt/sources.list for debian buster on x86_64
  ansible.builtin.set_fact:
    sources_filename: debian-buster.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "buster"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# debian bullseye
- name: Configuring /etc/apt/sources.list for debian bullseye on x86_64
  ansible.builtin.set_fact:
    sources_filename: debian-bullseye.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "bullseye"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# debian bookworm
- name: Configuring /etc/apt/sources.list for debian bookworm on x86_64
  ansible.builtin.set_fact:
    sources_filename: debian-bookworm.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "bookworm"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# debian trixie
- name: Configure sources for debian trixie on x86_64
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "trixie"
    - ansible_architecture|lower == "x86_64"
  block:
    - name: Configuring /etc/apt/sources.list for debian trixie on x86_64
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: "# Debian sources have moved to /etc/apt/sources.list.d/debian.sources"
        owner: root
        mode: "0644"
      become: true
      become_user: root

    - name: Configuring /etc/apt/sources.list.d/debian.sources for debian trixie on x86_64
      ansible.builtin.set_fact:
        sources_filename: debian-trixie.jinja2
        sources_dest: /etc/apt/sources.list.d/debian.sources
      become: true
      become_user: root

## armv6l/armv7l/aarch64 (aka raspberry pis)
# debian buster
- name: Configuring /etc/apt/sources.list for debian buster on armv7l
  ansible.builtin.set_fact:
    sources_filename: debian-buster.jinja2
    sources_dest: /etc/apt/sources.list
    raspi_sources_filename: raspian-buster-raspi.jinja2
    raspi_sources_dest: /etc/apt/sources.list.d/raspi.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "buster"
    - ansible_architecture|lower in apt_source_arm_versions
  become: true
  become_user: root

# debian bullseye
- name: Configuring /etc/apt/sources.list for debian bullseye on armv7l
  ansible.builtin.set_fact:
    sources_filename: debian-bullseye.jinja2
    sources_dest: /etc/apt/sources.list
    raspi_sources_filename: raspian-bullseye-raspi.jinja2
    raspi_sources_dest: /etc/apt/sources.list.d/raspi.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "bullseye"
    - ansible_architecture|lower in apt_source_arm_versions
  become: true
  become_user: root

# debian bookworm
- name: Configuring /etc/apt/sources.list for debian bookworm on armv7l
  ansible.builtin.set_fact:
    sources_filename: debian-bookworm.jinja2
    sources_dest: /etc/apt/sources.list
    raspi_sources_filename: raspian-bookworm-raspi.jinja2
    raspi_sources_dest: /etc/apt/sources.list.d/raspi.list
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "bookworm"
    - ansible_architecture|lower in apt_source_arm_versions
  become: true
  become_user: root

# debian trixie
- name: Configure sources for debian trixie on arm
  when:
    - ansible_distribution|lower == "debian"
    - ansible_distribution_release|lower == "trixie"
    - ansible_architecture|lower in apt_source_arm_versions
  block:
    - name: Configuring /etc/apt/sources.list for debian trixie on arm
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: "# Debian sources have moved to /etc/apt/sources.list.d/debian.sources"
        owner: root
        mode: "0644"
      become: true
      become_user: root

    - name: Remove old raspi.list file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/raspi.list
        state: absent
      become: true
      become_user: root

    - name: Configuring /etc/apt/sources.list.d/debian.sources for debian trixie on arm
      ansible.builtin.set_fact:
        sources_filename: raspian-trixie.jinja2
        sources_dest: /etc/apt/sources.list.d/debian.sources
        raspi_sources_filename: raspian-trixie-raspi.jinja2
        raspi_sources_dest: /etc/apt/sources.list.d/raspi.sources
      become: true
      become_user: root

# xbian stretch
- name: Configuring /etc/apt/sources.list for xbian stretch on armv7l
  ansible.builtin.set_fact:
    sources_filename: xbian-debian-stretch.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "xbian"
    - ansible_architecture|lower in apt_source_arm_versions
  become: true
  become_user: root

## x86_64
# ubuntu jammy
- name: Configuring /etc/apt/sources.list for ubuntu jammy on x86_64
  ansible.builtin.set_fact:
    sources_filename: ubuntu-jammy.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "ubuntu"
    - ansible_distribution_release|lower == "jammy"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# ubuntu jammy
- name: Configuring /etc/apt/sources.list for ubuntu jammy on x86_64
  ansible.builtin.set_fact:
    sources_filename: ubuntu-jammy.jinja2
    sources_dest: /etc/apt/sources.list
  when:
    - ansible_distribution|lower == "ubuntu"
    - ansible_distribution_release|lower == "jammy"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# ubuntu noble
- name: Configuring /etc/apt/sources.list.d/ubuntu.sources for ubuntu noble on x86_64
  ansible.builtin.set_fact:
    sources_filename: ubuntu-noble.jinja2
    sources_dest: /etc/apt/sources.list.d/ubuntu.sources
  when:
    - ansible_distribution|lower == "ubuntu"
    - ansible_distribution_release|lower == "noble"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# linuxmint xia
- name: Configuring /etc/apt/sources.list.d/official-package-repositories.list for Linux Mint xia on x86_64
  ansible.builtin.set_fact:
    sources_filename: mint-xia.jinja2
    sources_dest: /etc/apt/sources.list.d/official-package-repositories.list
  when:
    - ansible_distribution|lower == "linux mint"
    - ansible_distribution_release|lower == "xia"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# linuxmint zara
- name: Configuring /etc/apt/sources.list.d/official-package-repositories.list for Linux Mint zara on x86_64
  ansible.builtin.set_fact:
    sources_filename: mint-zara.jinja2
    sources_dest: /etc/apt/sources.list.d/official-package-repositories.list
  when:
    - ansible_distribution|lower == "linux mint"
    - ansible_distribution_release|lower == "zara"
    - ansible_architecture|lower == "x86_64"
  become: true
  become_user: root

# writing the apt sources files from variable above
- name: "Writing /etc/apt/sources.list or /etc/apt/sources.list.d/debian.sources from {{ sources_filename }}"
  ansible.builtin.template:
    src: "{{ sources_filename }}"
    dest: "{{ sources_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify: Updating sources
  when: sources_filename is defined
  become: true
  become_user: root

- name: "Writing /etc/apt/sources.list.d/raspi.list from {{ raspi_sources_filename }}"
  ansible.builtin.template:
    src: "{{ raspi_sources_filename }}"
    dest: "{{ raspi_sources_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify: Updating sources
  when: raspi_sources_filename is defined
  become: true
  become_user: root

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
